### PR TITLE
Replace new lines with <br/> tags

### PR DESCRIPTION
**Pull request by cokert**
This addresses #13 by replacing new lines with <br/> tags.  Another option is to do the replacement in the vue code client side.

### CODE REVIEW

**Comment by kendavis2** [comment]
Should this be a new function of its own called `format` instead of added to the `mutate` function? Any future formatting can then be abstracted away in the  `format` function. 
```			
commit.Commit.Message = mutate(commit.Commit.Message, commitConfig.ExistingValue, commitConfig.NewValue)

commit.Commit.Message = tokenize(commit, targetTag)
 // new function
commit.Commit.Message = format(commit.Commit.Message)
```

**Comment by cokert** [comment]
Yeah, I was kind a thinking the same.  But was more concerned about whether it was better to do this here or on the client.  I'll push this out into a new function later this evening.

**Comment by cokert** [comment]
Ok, I created a new function for display formatting concerns.  Right now it just replaces new lines, but could do more in the future.

**Comment by cokert** [comment]
I'm closing this because I moved the formatting into the browser/vue code.  I'll create another PR for that shortly.

**Pull request closed without merging**
